version: '1.1.1'
services:
  webapplication1:
    image: takuto1127/battari-summarize-conversation:1.1.1
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/cred/google-credentials.json
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAIN_BACKEND_URL: ${MAIN_BACKEND_URL}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/cred:/etc/cred
